name: Build and Publish Linux Android Xiaomi Ginkgo Package

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains three jobs: "build", "prepare", and "publish"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Use an ARM64-based container image
    container: quay.io/droidian/build-essential:trixie-arm64

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Update repositories
        run: |
          dpkg --add-architecture arm64
          apt update

      - name: Install dependencies for cross-build
        run: apt install -y --allow-downgrades devscripts equivs crossbuild-essential-arm64

      - name: Install dependencies for package build
        run: |
          mk-build-deps --host-arch arm64 --install --tool='apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends --yes' debian/control
          rm linux*.deb

      - name: Build package
        run: |
          dpkg-buildpackage -us -uc -b --host-arch arm64

      - name: Move packages to out directory
        run: |
          mkdir /out
          cp ../*.deb /out/
          ls /out

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-android-xiaomi-ginkgo
          path: /out/*.deb
          if-no-files-found: error
          retention-days: 1

  prepare:
    runs-on: ubuntu-20.04
    name: Create GitHub release
    needs: build

    steps:
      - name: Delete old latest release
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          delete_release: true # default: false
          tag_name: latest # tag name to delete
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag latest
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest

  publish:
    runs-on: ubuntu-20.04
    needs: prepare

    name: Publish linux-android-xiaomi-ginkgo

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: out

      - name: Create latest release
        uses: softprops/action-gh-release@v1
        with:
          files: out/linux-android-xiaomi-ginkgo/*.deb
          tag_name: latest
          draft: false
          prerelease: false

